### ISSUE TITLE
Need alternatives to VirtualBox as it doesn't support ARM

### ISSUE THREAD

**Issue by oglinuk** [rwxrob/boost#11]
https://www.virtualbox.org/ticket/17762

"VirtualBox is an x86 emulator. I don't think that an ARM port (or a PowerPC, or a Sparc, or a <InsertFavoriteArchitectureHere>) will ever happen."

This means anyone using [M1](https://www.eetasia.com/teardown-identifying-apple-m1s-distinct-circuit-blocks/) hardware needs an alternative.

Found some possible alternatives

* https://www.arthurkoziel.com/running-virt-manager-and-libvirt-on-macos/
* https://github.com/billyan2018/vagrant-qemu

**Comment by Destrocamil** [comment]
I am testing UTM as we speak, I really don't know if this if a fit.

**Comment by andrewcrook** [comment]
> VirtualBox is an x86 emulator.

No it's not an emulator and that’s apart of the problem. 

It's virtualisation it uses the virtualisation extensions of the hardware CPU i.e Intel-VT or AMD-V.
You could try the UTM which use QEMU  it uses emulation for Intel support on ARM but it's dead slow.
Or just use ARM64 Native Linux in UTM/QEMU/Parallels/VMWARE this will use ARM64's hardware virtualisation extensions.

If you need x86 64bit support macOS 13 looks to offer a new solution run an ARM64 VM with a ARM64 Linux and with some configuration and a few Linux tools you can make it use Rosetta 2 to add x86_64 support to the Linux instance which can then run 64bit Intel code through Rosetta’s translation. There is a 23% performance hit for the x86 code but its probably better than QEMU. I expect once macOS 13 is out of beta virtualisation software will adopt this method and make the setup automated.

> It will also be interesting to see if ultimately this works well for graphics programs too and if Vulkan be wrangled to work in the stack using the likes of MoltenVK for in turn allowing Linux games to work on Apple Silicon -- or Steam Play for Windows games on Linux on macOS.
... also how this could be use with containers. 

[Create macOS or Linux virtual machines
Learn how you can use the Virtualization framework to quickly create virtual machines on your Mac. We'll show you how to create a virtual Mac and quickly test changes to your app in an isolated environment. We'll also explore how you can install and run full Linux distributions on Apple silicon, and share how you can take advantage of Rosetta 2 to run x86-64 Linux binaries.](https://developer.apple.com/videos/play/wwdc2022/10002/)

[Running Intel Binaries in Linux VMs with Rosetta - Run x86_64 Linux binaries under ARM Linux on Apple silicon.](https://developer.apple.com/documentation/virtualization/running_intel_binaries_in_linux_vms_with_rosetta)

[With macOS 13 virtualization I can totally work with Qt Creator and develop for x86_64 gcc target using Rosetta 2, which is wild. it’s pretty smooth!](https://twitter.com/penk/status/1534585190579838978)

**Comment by rwxrob** [comment]
Yeah, we moved to VMWare officially for the boost, but some will use QEMU/libvirt/KVM as well.
